### ISSUE TITLE
Countdown timer on iPad

### ISSUE THREAD

**Issue by xLink** [kbwood/countdown#31]
Got an issue where the timer isnt running atall on the iPad 2, chrome & safari tested. Would be grateful if you could look into this?

**Comment by RajeebTheGreat** [comment]
@kbwood Any update on this issue? It doesn't work on Safari browser.

**Comment by Mohsen-Khakbiz** [comment]
I was using this format "2020,05,06" and didn't work on Safari and iphone; http://take.ms/I3vDG
but after changing it to "2020-05-06" it worked perfectly http://take.ms/3yJ8y

**Comment by Mohsen-Khakbiz** [comment]
for me this solution worked perfect https://stackoverflow.com/a/5646753
