### ISSUE TITLE
Excessive cpu usage

### ISSUE THREAD

**Issue by mszyndel** [kbwood/countdown#49]
Using this plugin I noticed that in some browsers it causes very high CPU usage. It's certainly not a problem with the plugin itself, rather the browsers, but I started wondering if the plugin needs to fire up events many times a second when a countdown is clearly performed once per second?

Additionally this behaviour was noticed even on the pages which don't have any counter, only js file included.

![screen shot 2014-07-28 at 22 35 54](https://cloud.githubusercontent.com/assets/354046/3726786/d2f03128-1696-11e4-9066-d3ab8a067be4.png)

**Comment by jeremyhaile** [comment]
I'm fighting this issue as well. I've been noticing CPUs pegged at 100% and debugged it down to this plugin.

**Comment by jeremyhaile** [comment]
The timerCallback is literally called 60 times per second, which seems super inefficient.
