### ISSUE TITLE
Split second difference between different browser tabs

### ISSUE THREAD

**Issue by KushtrimPacaj** [kbwood/countdown#59]
I just used this countdown on my auction project, and noticed that there is a split second difference between browser tabs ( and between different browsers) 
This is also visible in the example page: http://keith-wood.name/countdownBasics.html

Is this a bug in the plugin, or is there something wrong with my system?
![jquery countdown basics difference](https://cloud.githubusercontent.com/assets/8522712/5602686/4e56780a-935f-11e4-9d31-2652837a2334.PNG)

**Comment by kbwood** [comment]
Each tab has it's own timer that updates once a second, so it's possible that two tabs are slightly different.
