### ISSUE TITLE
Significant and showing seconds when time left is < 2 minutes

### ISSUE THREAD

**Issue by pederjohnsen** [kbwood/countdown#60]
Is there an easy way to make the counter show the time left in seconds if there is only 2 minutes left?

I actually want my timer to initially only show days, then when less than 3 days left I want it to show the hours left, then when less than 3 hours left show it in minutes and then as mentioned above when only 2 minutes left show it in seconds..

**Comment by kbwood** [comment]
You would need to use the onTick callback to monitor the time, and then use the 'option' method to change the format option. See the "Highlight last five seconds" example on the Miscellaneous tab on the Web site.

**Comment by pederjohnsen** [comment]
Brilliant, thanks! :+1:
