### ISSUE TITLE
Issue Accessing Muliple Periods in onTick function

### ISSUE THREAD

**Issue by Bizarro181** [kbwood/countdown#71]
I have the following countdown timer setup
```javascript
$('#main-timer').countdown({
	until: +3600, 
	format: 'MS', 
	compact:true,
	onTick: function(periods){
		if(periods[5] == 6 && periods[6] == 8){
			playWarning();
		}
		if(periods[5] == 0){
			playTimeup();
		}
	},
	tickInterval: 60,
	layout: '<p><span class="unit">{m10}</span><span class="unit">{m1}</span>:<span class="unit">{s10}</span><span class="unit">{s1}</span></span>'
});
```
And that first if statement never triggers (I'm looking for it to fire at 6 minutes and 8 seconds), however if I change that to 
```javascript
if(periods[5] == 6){
```
It works fine, however I'd really like to be able to access minutes and seconds rather than just seconds.  Is this working properly or am I misunderstanding how to use periods

**Comment by kbwood** [comment]
You have a tickInterval of 60, so it will only call the onTick function every 60 seconds. The seconds value will never be 8. Remove the tickInterval value, or make it 2 or 4.
